import Head from 'next/head'
import Image from 'next/image'
import Link from "next/link";
import useUser from "@/lib/useUser";
import clientPromise from "@/lib/mongodb";
import ColorChange from "@/components/color-change-button";
import styles from "../styles/Home.module.css";

export default function Home({ isConnected }) {
  const { user } = useUser();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ColorChange />
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        {user?.isLoggedIn ? (
          <p className={styles.description}>Welcome Captain {user.email}</p>
        ) : (
          <p className={styles.description}>
            You are not Logged In <Link href="/login">Please Login</Link>
          </p>
        )}
        {isConnected ? (
          <h2 className="subtitle">You are connected to MongoDB</h2>
        ) : (
          <h2 className="subtitle">
            You are NOT connected to MongoDB. Check the <code>README.md</code>{" "}
            for instructions.
          </h2>
        )}
        <div className={styles.grid}>
          <Link href="visit">
            <a className={styles.card}>
              <h2>Patient Visit &rarr;</h2>
              <p>Record new Patient Visit!!&nbsp;&nbsp;&nbsp;&nbsp;</p>
              <p>&nbsp;&nbsp;</p>
            </a>
          </Link>

          <Link href="new-patient">
            <a className={styles.card}>
              <h2>Add new Patient &rarr;</h2>
              <p>Gathering details of new Patient</p>
            </a>
          </Link>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export async function getServerSideProps() {
  try {
    // client.db() will be the default database passed in the MONGODB_URI
    // You can change the database by calling the client.db() function and specifying a database like:
    // const db = client.db("myDatabase");
    // Then you can execute queries against your database like so:
    // db.find({}) or any of the MongoDB Node Driver commands
    await clientPromise;
    return {
      props: { isConnected: true },
    };
  } catch (e) {
    console.error(e);
    return {
      props: { isConnected: false },
    };
  }
}
